# k8s/hpa.yaml
# -------------
# Horizontal Pod Autoscaler.
# Automatically adds more pods when CPU usage is high,
# and removes pods when usage drops to save cost.

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: financial-analyst-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: financial-analyst-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80